In [1]:
import pandas as pd
df1=pd.read_csv('table1_1.csv')
df2=pd.read_csv('table1_2.csv')
df3=pd.read_csv('table1_3.csv')
df4=pd.read_csv('table1_4.csv')

In [2]:
Table1 = pd.concat([df1, df2,df3,df4], ignore_index=True)

In [3]:
Table1

,SNo,Brandname,Category,Price,ProductName,occasion,returntime
0,1,Adidas,Men • Cricket,₹999.00,INDIA CRICKET ODI FAN JERSEY,Men • Cricket,Secure transactions with hassle free 14 days E...
1,2,Adidas,Men • Football,₹5 299.00,REAL MADRID 23/24 HOME JERSEY,Men • Football,Secure transactions with hassle free 14 days E...
2,3,Adidas,Men • Fear of God Athletics,₹18 999.00,FEAR OF GOD ATHLETICS SUEDE FLEECE SHORTS,Men • Fear of God Athletics,Secure transactions with hassle free 14 days E...
3,4,Adidas,Men • Fear of God Athletics,₹16 999.00,FEAR OF GOD ATHLETICS MUSCLE SWEATSHIRT,Men • Fear of God Athletics,Secure transactions with hassle free 14 days E...
4,5,Adidas,Men • Fear of God Athletics,₹21 999.00,FEAR OF GOD ATHLETICS HEATHER TRACK JACKET,Men • Fear of God Athletics,Secure transactions with hassle free 14 days E...
...,...,...,...,...,...,...,...
573,574,Adidas,Men • Sportswear,₹3 299.00,TIRO WORDMARK SHORTS,Men • Sportswear,Secure transactions with hassle free 14 days E...
574,575,Adidas,Women • Running,₹3 999.00,RUNNING ESSENTIALS 7/8 LEGGINGS,Women • Running,Secure transactions with hassle free 14 days E...
575,576,Adidas,Men • Swim,₹2 299.00,CLOUDFOAM M,Men • Swim,Secure transactions with hassle free 14 days E...
576,577,Adidas,Men • Originals,₹5 599.00,ADICOLOR CLASSICS FIREBIRD TRACK PANTS,Men • Originals,Secure transactions with hassle free 14 days E...
577,578,Adidas,Women • Originals,₹4 599.00,TANK DRESS,Women • Originals,Secure transactions with hassle free 14 days E...